#!/bin/bash
#
# Copyright (c) 2017 Gaël PORTAY <gael.portay@savoirfairelinux.com>
#
# This program is free software: you can redistribute it and/or modify
# the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#

set -e

next=1
for mbox in "$@"; do
	index="$(printf "%04i" "$next")"
	sed -e '/Subject: /s,^Subject: \[PATCH\( [0-9]\+/[0-9]\+\)\?\] \(.*\)$,\2\n,p' \
	    -e '1,/^$/d' \
	       "$mbox" >"$index.patch"
	subject="$(head -n1 "$index.patch")"
	patch="$index-$subject.patch"
	patch="${patch//:/}"
	patch="${patch// /-}"
	mv "$index.patch" "$patch"
	echo "$patch"
	next="$((next+1))"
done
