= git-patch(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: The Missing Git Commands Manual
:man source: The Missing Git Commands Project

== NAME

git-patch - Apply a series of patches

== SYNOPSIS

*git-patch* [--autoresolve] [--signoff] [--keep] [--no-utf8] [--3way] [--quiet]
[--scissors] [(<mbox> | <unified>)...]

*git-patch* [--signoff] [--keep] [--[no-]keep-cr] [--[no-]utf8] [--3way]
[--quiet] [(<mbox> | <unified>)...]

*git-patch* (--continue | --skip | --abort | --status | --resolve |
--show-current-patch)

== DESCRIPTION

Reads the supplied mailbox or unified output (i.e. "a patch") and applies it to
files.

When a patch is supplied, this command applies the patch and creates a commit.

When git apply fails, it apply the parts of the patch that are applicable, and
leave the rejected hunks in corresponding *.rej files.

== OPTIONS

(<mbox>|<unified>)...::
    The list of mailbox or unified files to read patches from. If you do not
    supply this argument, the command reads from the standard input.

--autoresolve::
    Try to automatically resolve rejected hunks. First 3-way merges unpatched
    files; then applies rejects with a 2-lines context, and finally a
    single-line context.

-s, --signoff::
    Add a Signed-off-by: line to the commit message, using the committer
    identity of yourself. See the signoff option in git-commit(1) for more
    information.
    This flag is passed to the git am (see git-am(1)) and git commit (see
    git-commit(1)) programs that apply and commit the patch.

-k, --keep::
    Pass -k flag to git mailinfo (see git-mailinfo(1)).

--keep-non-patch::
    Pass -b flag to git mailinfo (see git-mailinfo(1)).

--[no-]keep-cr::
    With --keep-cr, call git mailsplit (see git-mailsplit(1)) with the same
    option, to prevent it from stripping CR at the end of lines.  am.keepcr
    configuration variable can be used to specify the default behaviour.
    --no-keep-cr is useful to override am.keepcr.

-c, --scissors::
    Remove everything in body before a scissors line (see git-mailinfo(1)). Can
    be activated by default using the mailinfo.scissors configuration variable.

--no-scissors::
    Ignore scissors lines (see git-mailinfo(1)).

-m, --message-id::
    Pass the -m flag to git mailinfo (see git-mailinfo(1)), so that the
    Message-ID header is added to the commit message. The am.messageid
    configuration variable can be used to specify the default behaviour.

-u, --utf8::
    Pass -u flag to git mailinfo (see git-mailinfo(1)). The proposed commit log
    message taken from the e-mail is re-coded into UTF-8 encoding (configuration
    variable i18n.commitencoding can be used to specify project’s preferred
    encoding if it is not UTF-8).

    This was optional in prior versions of git, but now it is the default. You
    can use --no-utf8 to override this.

--no-utf8::
    Pass -n flag to git mailinfo (see git-mailinfo(1)).

-3, --3way::
    When the patch does not apply cleanly, fall back on 3-way merge if the patch
    records the identity of blobs it is supposed to apply to, and we have those
    blobs available locally, possibly leaving the conflict markers in the files
    in the working tree for the user to resolve. This option implies the --index
    option, and is incompatible with the --reject and the --cached options.
    This flag is passed to the git am (see git-am(1)) and git apply (see
    git-apply(1)) programs that apply the patch.

-q, --quiet::
    Be quiet. Only print error messages.

--skip::
    Skip the current patch. This is only meaningful when restarting an aborted
    patch.

--continue::
    After a patch failure (e.g. attempting to apply conflicting patch), the user
    has applied it by hand and the index file stores the result of the
    application. Make a commit using the authorship and commit log extracted
    from the e-mail message and the current index file, and continue.

--abort::
    Restore the original branch and abort the patching operation.

--status::
    Compare original patch to patching operation.

--resolve::
    Try to automatically resolve rejected hunks. See --autoresolve option.

--show-current-patch::
	Show the patch being applied when "git am" is stopped because of
	conflicts.

== HOOKS

This command run either *am* or, *apply* and *commit*.

== BUGS

Report bugs at *https://github.com/gportay/git-missings/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright (c) 2017-2018 Gaël PORTAY

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.

== SEE ALSO

git-am(1), git-apply(5)
