#!/bin/bash
#
# Copyright (c) 2017-2018 Gaël PORTAY
#
# SPDX-License-Identifier: GPL-3.0
#

set -e
set -o pipefail

# The following function is based on code from:
#
# bash/zsh completion support for core Git.
#
# Copyright (C) 2006,2007 Shawn O. Pearce <spearce@spearce.org>
# Conceptually based on gitcompletion (http://gitweb.hawaga.org.uk/).
# Distributed under the GNU General Public License, version 2.0.
#
# Discovers the path to the git repository taking any '--git-dir=<path>' and
# '-C <path>' options into account and stores it in the $__git_repo_path
# variable.
__git_find_repo_path ()
{
	if [ -n "$__git_repo_path" ]; then
		# we already know where it is
		return
	fi

	if [ -n "${__git_C_args-}" ]; then
		__git_repo_path="$(git "${__git_C_args[@]}" \
			${__git_dir:+--git-dir="$__git_dir"} \
			rev-parse --absolute-git-dir 2>/dev/null)"
	elif [ -n "${__git_dir-}" ]; then
		test -d "$__git_dir" &&
		__git_repo_path="$__git_dir"
	elif [ -n "${GIT_DIR-}" ]; then
		test -d "${GIT_DIR-}" &&
		__git_repo_path="$GIT_DIR"
	elif [ -d .git ]; then
		__git_repo_path=.git
	else
		__git_repo_path="$(git rev-parse --git-dir 2>/dev/null)"
	fi
}

log() {
	$QUIET || echo "$*" >&2
}

fatal() {
	echo "fatal: $*" >&2
	exit 1
}

oops() {
	local abort_safety
	local hint

	trap - 0

	hint="Use 'git patch --quit' to abort and keep HEAD where it is"
	if abort_safety="$(cat "$gitpatchdir/abort-safety" 2>/dev/null)"; then
		hint+="\n      or 'git reset --hard $abort_safety' to restore the original branch and abort the patching operation"
	fi
	hint "$hint"
	
	fatal "${*:-Oops!}"
}

hint() {
	echo -e "\e[33mhint: $*\e[0m" >&2
}

hint_and_exit() {
	hint "${*:-Use 'git patch --show-current-patch' to see the failed patch}"
	cat <<EOF
When you have resolved this problem, run "git patch --continue".
If you prefer to skip this patch, run "git patch --skip" instead.
To restore the original branch and stop patching, run "git patch --abort".
EOF
	exit 1
}

prompt_yes_no() {
	local choices
	local resp

	while read -r -p "$*? " resp; do
		if [[ ${resp,,} =~ ^(y|yes|n|no|)$ ]]; then
			break
		fi

		echo "$resp: Invalid response!" >&2;
		unset resp
	done

	if [ -z "$resp" ]; then
		read -a choices < <(echo "${2//\//] [}")
		resp="${choices[0]}"
	else
		resp="[$resp]"
	fi

	if [[ "${resp,,}" =~ ^\[(y|yes)\]$ ]]; then
		return 0
	fi

	return 1
}

extract_mailbox_header() {
	sed -e '/^$/,$d' \
	       "$1"
}

extract_mailbox_body() {
	sed -e '1,/^$/d' \
	       "$1"
}

extract_mailbox_info() {
	extract_mailbox_header "$1" |
	sed -e '/From: /s,From: \(.*\) <\(.*\)>,Author: \1\nEmail: \2,p' \
	    -e '/Subject: /s,\[PATCH\( [0-9]\+/[0-9]\+\)\?\] ,,p' \
	    -e '/Date: /p' \
	    -n
	echo
}

extract_mailbox_author_script() {
	extract_mailbox_header "$1" |
	sed -e '/From: /s,From: \(.*\) <\(.*\)>,GIT_AUTHOR_NAME="\1"\nGIT_AUTHOR_EMAIL="\2",p' \
	    -e '/Date: /s,Date: \(.*\),GIT_AUTHOR_DATE="\1",p' \
	    -n
}

extract_mailbox_subject() {
	sed -e '/Subject: /s,Subject: ,,p' \
	    -n "$1"
}

extract_mailbox_commit_message() {
	extract_mailbox_body "$1" | \
	sed -e '/^---$/,$d'
}

extract_mailbox_patch() {
	extract_mailbox_body "$1" | \
	sed -e '/^---/,$p' \
	    -n
}

extract_diff_commit_message() {
	sed -e '/^diff /,$d' \
	    -e '/^--- /,$d' \
	    -e '/^+++ /,$d' \
	       "$1"
}

sanitized_mailbox_subject() {
	# shellcheck disable=SC2001
	echo "$*" | \
	sed -e 's,\[PATCH\( [0-9]\+/[0-9]\+\)\?\] ,,'
}

sanitized_diff_commit_message() {
	echo "$*" | \
	sed -e 's,^.*/,,' \
	    -e 's,^[0-9]*[_-],,' \
	    -e 's,\.patch,,' \
	    -e 's,[_-], ,g'
}

index_to_filename() {
	sed -e "$1p" \
	    -n "$gitpatchdir/todo"
}

get_new_files() {
	# error: path/to/file: already exists in working directory
	sed -e '/error: /s,^error: \(.*\): already exists in working directory$,\1,p' \
	    -n "$gitpatchdir/applying"
}

get_patched_files() {
	# Applied patch path/to/file cleanly.
	sed -e '/^Applied patch /s,Applied patch \(.*\) cleanly.$,\1,p' \
	    -n "$gitpatchdir/applying"
}

get_reject_files() {
	# Applying patch path/to/file with x reject[s]...
	sed -e '/Applying patch /s,Applying patch \(.*\) with [0-9]* rejects\?...$,\1.rej,p' \
	    -n "$gitpatchdir/applying"
}

get_unpatched_files() {
	# error: path/to/file: does not [exist in|match] index
	sed -e '/error: /s,^error: \(.*\): does not \(exist in\|match\) index$,\1,p' \
	    -n "$gitpatchdir/applying"
}

get_unpatched_rejects() {
	get_unpatched_files | \
	while read -r f; do
		echo "$f.rej"
	done
}

get_new_files_rejects() {
	get_new_files | \
	while read -r f; do
		echo "$f.rej"
	done
}

get_all_artifacts_files() {
	get_new_files
	get_reject_files
	get_unpatched_rejects
}

echo_checking_patch_and_reject() {
	echo "Checking patch $1"
	sed -e "/^Checking patch ${1//\//\\/}/,/^\(Checking patch \|$\)/{//d;p}" \
	    -n "$gitpatchdir/applying"
	cat "$1.rej"
}

check_for_new_files() {
	get_new_files | \
	while read -r f; do
		if ! git status --porcelain "$f" | grep -q "^A  $f"; then
			hint_and_exit "Use 'git add \"$f\"' to update index"
		fi
	done
}

check_for_rej_files() {
	get_reject_files | \
	while read -r rej; do
		f="${rej%*.rej}"
		if [ -e "$rej" ]; then
			echo_checking_patch_and_reject "$f"
			if check_for_diff_file "$f"; then
				hint "Use 'rm -f $rej && git patch --continue' to remove the reject and continue"
				echo "The conflict looks to be resolved!" >&2
				exit 1
			fi

			echo "Remaining reject artifact $rej!" >&2
			echo "Resolve the conflict first and remove the file then." >&2
			if ! git status --porcelain "$f" | grep -q "^M  $f"; then
				hint_and_exit "Use 'git add \"$f\"' to update index"
			fi
			hint_and_exit "Use '$(git config --get diff.tool || echo vimdiff) \"$f\" \"$rej\"' to apply the chunks manually"
		fi
	done
}

check_for_unpatched_files() {
	get_unpatched_files | \
	while read -r f; do
		rej="$f.rej"
		if [ -e "$rej" ]; then
			echo_checking_patch_and_reject "$f"
			if check_for_diff_file "$f"; then
				hint "Use 'rm -f $rej && git patch --continue' to remove the reject and continue"
				echo "The conflict looks to be resolved!" >&2
				exit 1
			fi

			echo "Remaining unpatched artifact $rej!" >&2
			echo "Resolve the conflict first and remove the file then." >&2
			if ! git status --porcelain "$f" | grep -q "^M  $f"; then
				hint_and_exit "Use 'git add \"$f\"' to update index"
			fi
			hint_and_exit "Use '$(git config --get diff.tool || echo vimdiff) \"$f\" \"$rej\"' to apply the chunks manually"
		fi
	done
}

check_for_artifacts() {
	check_for_rej_files
	check_for_unpatched_files
	check_for_new_files
}

check_for_diff() {
	status_patch_changes_only |
	diff -ud --label "patch" --label "cached" --color \
	     - <(status_cached_changes_only)
}

check_for_diff_file() {
	status_patch_file_changes_only "$@" |
	diff -ud --label "patch" --label "cached" --color \
	     - <(status_cached_file_changes_only "$@")
}

add_new_files_to_index() {
	get_new_files | \
	while read -r f; do
		git add "$f"
	done
}

add_patched_files_to_index() {
	get_patched_files | \
	while read -r f; do
		git add "$f"
	done
}

add_unpatched_files_to_index() {
	get_unpatched_files | \
	while read -r f; do
		git add "$f"
	done
}

saving_unpatched_files_to_rej() {
	get_unpatched_files | \
	while read -r f; do
		if [ "$f" != "${f%/*}" ]; then
			mkdir -p "${f%/*}"
		fi
		sed -e "/--- .*.\\+\\/${f//\//\\\/}/,/^\(diff .*\|\)$/{//d;/^+++/d;/^index /d;p}" \
		    -e "1i--- a/$f\n+++ b/$f" \
		    -n "$gitpatchdir/patch" \
		    >"$f.rej"
	done
}

remove_all_artifacts() {
	get_all_artifacts_files | xargs rm -f
}

next() {
	next="$((next + 1))"
	echo "$next" >"$gitpatchdir/next"
	rm -f "$gitpatchdir/patch" \
	      "$gitpatchdir/final-commit" \
	      "$gitpatchdir/applying"
}

commit() {
	local GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_AUTHOR_DATE

	if [ "$(git status --porcelain --untracked-files=no | wc -l)" -eq 0 ]; then
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.
When you have resolved this problem, run "git patch --continue".
If you prefer to skip this patch, run "git patch --skip" instead.
To restore the original branch and stop patching, run "git patch --abort".
EOF
		exit 1
	fi

	# shellcheck disable=SC1091
	. "$gitpatchdir/author-script"

	# shellcheck disable=SC2086
	GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-$(git config --get user.name)}" \
	GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-$(git config --get user.email)}" \
	GIT_AUTHOR_DATE="${GIT_AUTHOR_DATE:-$(date --rfc-email)}" \
	git commit $COMMITOPTS --file "$gitpatchdir/final-commit" "$@"
}

edit_commit() {
	if [ -t 0 ]; then
		set -- --edit "$@"
	fi

	commit "$@"
}

status_cached() {
	git diff --cached | \
	sed -e '/^diff /d' \
	    -e '/^index /d' \
	    -e '/^new file mode /d'
}

status_cached_changes_only() {
	status_cached | \
	sed -e '/^\(@@\| \)/d'
}

status_cached_file() {
	status_cached | \
	sed -e "/^--- .\\+\\/${1//\//\\\/}/,/^\(--- .*\|\)$/{//d;/^+++/d;p}" \
	    -n
}

status_cached_file_changes_only() {
	status_cached_file "$@" | \
	sed -e '/^\(@@\| \)/d'
}

status_patch() {
	sed -e '1,/^diff/d' \
	    -e '/^-- $/,$d' \
	    -e '/^diff /d' \
	    -e '/^index /d' \
	    -e '/^new file mode /d' \
	       "$gitpatchdir/patch"
}

status_patch_changes_only() {
	status_patch | \
	sed -e '/^\(@@\| \)/d'
}

status_patch_file() {
	status_patch | \
	sed -e "/^--- .\\+\\/${1//\//\\\/}/,/^\(--- .*\|\)$/{//d;/^+++/d;p}" \
	    -n
}

status_patch_file_changes_only() {
	status_patch_file "$@" | \
	sed -e '/^\(@@\| \)/d'
}

diff_tool() {
	local difftool

	difftool="$(git config --get diff.tool || echo vimdiff)"

	"$difftool" "$@"
}

resolve_unpatched() {
	for rej in $(get_unpatched_rejects); do
		[ -e "$rej" ] || continue

		oldfile="${rej%*.rej}"
		patchfile="$oldfile"
		while [ ! -e "$patchfile" ] &&
		      read -erp "File to patch for $rej [$oldfile]: " patchfile; do
			[ -n "$patchfile" ] || patchfile="$oldfile"
			[ -n "$patchfile" ] || continue
			if [ ! -e "$patchfile" ]; then
				echo "Error: $patchfile: No such file!" >&2
				continue
			fi
		done

		# Try applying reject in a treeway merge...
		if sed -e "s,$oldfile,$patchfile," "$rej" | \
		   git apply - -3; then
			git add "$patchfile"
			rm -f "$rej"
			break
		fi

		# Try applying and save rejects...
		if sed -e "s,$oldfile,$patchfile," "$rej" | \
		   git apply - --reject; then
			git add "$patchfile"
			rm -f "$rej"
			break
		fi

		# New rejects found!
		if [ "$patchfile.rej" != "$rej" ] &&
		   [ -e "$patchfile.rej" ]; then
			git add "$patchfile"
			rm -f "$rej"
			ln -sf "$(realpath "$patchfile.rej")" "$rej"
		fi

		# Manually merge
		if [ -t 0 ] && diff_tool "$rej" "$patchfile"; then
			if ! prompt_yes_no "Does conflicts are successfully merged" "[No/yes]"; then
				return 1
			fi

			git add "$patchfile"
			if [ -L "$rej" ]; then
				readlink "$rej" | xargs rm -f
			fi
			rm -f "$rej"
			break
		fi

		return 1
	done
}

resolve_rejected() {
	for rej in $(get_reject_files); do
		[ -e "$rej" ] || continue

		local patchfile
		patchfile="${rej%*.rej}"

		# Try applying reject in a treeway merge...
		if sed -e "/^diff a/a--- a/$patchfile\n+++ b/$patchfile" "$rej" | \
		   git apply - -3; then
			git add "$patchfile"
			rm -f "$rej"
			break
		fi

		# Try applying and save rejects...
		if sed -e "/^diff a/a--- a/$patchfile\n+++ b/$patchfile" "$rej" | \
		   git apply - --reject; then
			git add "$patchfile"
			rm -f "$rej"
			break
		fi

		# Manually merge
		if [ -t 0 ] && diff_tool "$rej" "$patchfile"; then
			if ! prompt_yes_no "Does conflicts are successfully merged" "[No/yes]"; then
				return 1
			fi

			git add "$patchfile"
			if [ -L "$rej" ]; then
				readlink "$rej" | xargs rm -f
			fi
			rm -f "$rej"
			break
		fi

		return 1
	done
}

autoresolve() {
	# Reduce context amount of lines
	if ! resolve_rejected -C2 --recount ||
	   ! resolve_rejected -C1 --recount; then
		return 1
	fi

	# Prompt for unpatch files
	if ! [ -t 0 ] ||
	   ! resolve_unpatched; then
		return 1
	fi
}

patch() {
	local msg index filename

	# Try to apply mailbox first
	# shellcheck disable=SC2086
	if git am $AMOPTS "$1"; then
		return
	fi

	# Applying mailbox failed
	# Make sure there is no apply-mbox in progress
	if [ -d "$gitdir/rebase-apply" ]; then
		log "Abort: \"$1\""
		git am --abort
	fi

	# Try to apply patch
	index="$(printf "%04i" "$next")"
	filename="$(index_to_filename "$index")"
	subject="$(extract_mailbox_subject "$1")"
	if [ -n "$subject" ]; then
		# patch is in mailbox format
		msg="$(sanitized_mailbox_subject "$subject")"
		extract_mailbox_commit_message "$1" >"$gitpatchdir/msg"
		extract_mailbox_patch "$1" >"$gitpatchdir/patch"
		extract_mailbox_info "$1" >"$gitpatchdir/info"
		extract_mailbox_author_script "$1" >"$gitpatchdir/author-script"
	else
		# patch is a diff format
		msg="$(sanitized_diff_commit_message "$filename")"
		extract_diff_commit_message "$1" >"$gitpatchdir/msg"
		cp "$1" "$gitpatchdir/patch"
		cat <<EOF >"$gitpatchdir/author-script"
GIT_AUTHOR_NAME='${GIT_AUTHOR_NAME:-$(git config --get user.name)}'
GIT_AUTHOR_EMAIL='${GIT_AUTHOR_EMAIL:-$(git config --get user.email)}'
GIT_AUTHOR_DATE='${GIT_AUTHOR_DATE:-$(date --rfc-email)}'
EOF
	fi

	# final-commit contains the commit message
	cat - "$gitpatchdir/msg" <<EOF >"$gitpatchdir/final-commit"
$msg

EOF

	$QUIET || echo "Applying: $msg"
	# shellcheck disable=SC2086
	if git apply $APPLYOPTS "$1" 2>&1 | \
	   tee "$gitpatchdir/applying" >&2; then
		commit
		return
	fi

	# Neither am nor apply succeed
	add_new_files_to_index
	add_patched_files_to_index
	add_unpatched_files_to_index
	saving_unpatched_files_to_rej

	# Try to auto-resolve
	if $AUTORESOLVE && autoresolve; then
		edit_commit
		return
	fi

	hint_and_exit "Use 'git patch --show-current-patch' to see the failed patch"
}

resolved() {
	edit_commit
	next
}

action_continue() {
	# No patch in progress... keep going
	if [ ! -f "$gitpatchdir/patch" ]; then
		fatal "No apply in progress?"
		return
	fi

	$QUIET || echo "Applying: $(head -n1 "$gitpatchdir/final-commit")"
	check_for_artifacts
	if ! check_for_diff; then
		hint "Use 'git patch --status' to see the differences side-by-side or 'git patch --resolved' if resolved"
		echo "Warning: changes are not rigorously identical!" >&2
		exit 1
	fi

	resolved
}

action_skip() {
	remove_all_artifacts
	next
}

action_abort() {
	# Reset current patchset
	trap 'oops "The impossible happened! Cannot recover :("' 0
	abort_safety="$(cat "$gitpatchdir/abort-safety")"
	remove_all_artifacts
	git reset --hard "$abort_safety"
	trap - 0

	# Remove context
	action_quit
}

action_quit() {
	rm -rf "$gitpatchdir/"
}

action_status() {
	if [ -z "$GIT_PAGER" ]; then
		GIT_PAGER="$(git config --get core.pager || echo "$PAGER")"
	fi
	if [ -z "$GIT_PAGER" ]; then
		GIT_PAGER="less"
	fi

	git diff --cached |
	diff --side-by-side --label "patch" --label "cached" --color=always \
	     "$gitpatchdir/patch" - | LESS="${LESS:-FRX}" LV="${LV:--c}" "$GIT_PAGER"
}

action_resolve() {
	# No patch in progress... keep going
	if [ ! -f "$gitpatchdir/patch" ]; then
		fatal "No apply in progress?"
		return
	fi

	$QUIET || echo "Applying: $(head -n1 "$gitpatchdir/final-commit")"
	autoresolve

	check_for_artifacts
	if ! check_for_diff; then
		if ! prompt_yes_no "Warning: changes are not rigorously identical, keep going" "[No/yes]"; then
			hint "Use 'git patch --status' to see the differences side-by-side or 'git patch --resolved' if resolved"
			exit 1
		fi
	fi

	resolved
}

action_resolved() {
	# No patch in progress... keep going
	if [ ! -f "$gitpatchdir/patch" ]; then
		fatal "No apply in progress?"
	fi

	$QUIET || echo "Applying: $(head -n1 "$gitpatchdir/final-commit")"
	resolved
}

action_show-current-patch() {
	cat "$gitpatchdir/patch"
}

usage() {
	cat <<EOF
usage: git patch [<options>] [(<mbox> | <unified>)...]
   or: git patch (--continue | --skip | --abort | --quit | --status | --resolve | --resolved | --show-current-patch)

        --autoresolve     try to auto-resolve rejects
        --continue        continue applying patches after resolving a conflict
        --skip            skip the current patch
        --abort           restore the original branch and abort the patching operation.
        --quit            abort the patching operation but keep HEAD where it is.
        --status          compare original patch to patching operation
        --resolve         try to automatically resolve rejected hunks
        --show-current-patch
                          show the patch being applied.
    -s, --signoff         add a Signed-off-by line to the commit message
    -3, --3way            attempt three-way merge if a patch does not apply
        --no-utf8         no recode into utf8
    -k, --keep            pass -k flag to git-mailinfo
    -m, --message-id      pass -m flag to git-mailinfo
    -c, --scissors        strip everything before a scissors line
    -q, --quiet           be quiet
EOF
}

__git_find_repo_path
gitdir="$__git_repo_path"
gitpatchdir="$gitdir/patch-apply"

t() {
	true
}

f() {
	false
}

AMOPTS=
APPLYOPTS=
COMMITOPTS=
ACTION=
AUTORESOLVE="f"
SIGN="f"
THREEWAY="f"
UTF8="t"
KEEP="f"
MESSAGEID="f"
SCISSORS="f"
QUIET="f"
while [ $# -ne 0 ]; do
	if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
		usage
		exit 0
	elif [ "$1" = "--autoresolve" ]; then
		AUTORESOLVE="t"
	elif [ "$1" = "-s" ] || [ "$1" = "--signoff" ]; then
		SIGN="t"
	elif [ "$1" = "-3" ] || [ "$1" = "--3way" ]; then
		THREEWAY="t"
	elif [ "$1" = "--no-utf8" ]; then
		UTF8="f"
	elif [ "$1" = "-k" ] || [ "$1" = "--keep" ]; then
		KEEP="t"
	elif [ "$1" = "-m" ] || [ "$1" = "--message-id" ]; then
		MESSAGEID="t"
	elif [ "$1" = "-c" ] || [ "$1" = "--scissors" ]; then
		SCISSORS="t"
	elif [ "$1" = "-q" ] || [ "$1" = "--quiet" ]; then
		QUIET="t"
	elif [ "$1" = "--continue" ]; then
		ACTION="continue"
		break
	elif [ "$1" = "--resolved" ]; then
		ACTION="resolved"
		break
	elif [ "$1" = "--skip" ]; then
		ACTION="skip"
		break
	elif [ "$1" = "--abort" ]; then
		ACTION="abort"
		break
	elif [ "$1" = "--quit" ]; then
		ACTION="quit"
		break
	elif [ "$1" = "--status" ]; then
		ACTION="status"
		break
	elif [ "$1" = "--resolve" ]; then
		ACTION="resolve"
		break
	elif [ "$1" = "--show-current-patch" ]; then
		ACTION="show-current-patch"
		break
	elif [ "$1" = "--" ]; then
		shift
		break
	else
		break
	fi
	shift
done

# First form [(<mbox> | <unified>)...]
if [ -z "$ACTION" ]; then
	# Make sure there is no apply-mbox in progress
	for dir in "$gitdir/rebase-apply" "$gitdir/patch-apply"; do
		if [ -d "$dir" ]; then
			fatal "previous rebase directory $dir still exists but patch given."
		fi
	done

	# Setup context
	mkdir "$gitpatchdir/"

	git rev-parse HEAD >"$gitpatchdir/abort-safety"

	if [ "$#" -eq 0 ]; then
		next="$((next+1))"
		index="$(printf "%04i" "$next")"
		cat - >"$gitpatchdir/$index"
		echo "stdin"
	else
		for patch in "$@"; do
			next="$((next+1))"
			index="$(printf "%04i" "$next")"
			cp "$patch" "$gitpatchdir/$index"
			echo "${patch##*/}"
		done
	fi >"$gitpatchdir/todo"

	last="$next"
	echo "$last" >"$gitpatchdir/last"

	next="1"
	echo "$next" >"$gitpatchdir/next"

	echo "$AUTORESOLVE" >"$gitpatchdir/autoresolve"
	echo "$SIGN" >"$gitpatchdir/sign"
	echo "$THREEWAY" >"$gitpatchdir/threeway"
	echo "$UTF8" >"$gitpatchdir/utf8"
	echo "$KEEP" >"$gitpatchdir/keep"
	echo "$MESSAGEID" >"$gitpatchdir/messageid"
	echo "$SCISSORS" >"$gitpatchdir/scissors"
	echo "$QUIET" >"$gitpatchdir/quiet"
# Second form (--continue | --skip | --abort | --quit)
else
	if [ ! -d "$gitpatchdir" ]; then
		fatal "Resolve operation not in progress, we are not resuming."
	fi

	if [ "$ACTION" != "quit" ]; then
		trap 'oops "The impossible happened! Cannot recover :("' 0
		next="$(cat "$gitpatchdir/next")"
		last="$(cat "$gitpatchdir/last")"
		trap - 0

		AUTORESOLVE="$(cat "$gitpatchdir/autoresolve" || echo "f")"
		SIGN="$(cat "$gitpatchdir/sign" || echo "f")"
		THREEWAY="$(cat "$gitpatchdir/threeway" || echo "t")"
		UTF8="$(cat "$gitpatchdir/utf8" || echo "t")"
		KEEP="$(cat "$gitpatchdir/keep" || echo "f")"
		MESSAGEID="$(cat "$gitpatchdir/messageid" || echo "f")"
		SCISSORS="$(cat "$gitpatchdir/scissors" || echo "f")"
		QUIET="$(cat "$gitpatchdir/quiet" || echo "f")"
	fi
fi

if $SIGN; then
	AMOPTS+=" --signoff"
	COMMITOPTS+=" --signoff"
fi

if $THREEWAY; then
	AMOPTS+=" --3way"
	APPLYOPTS+=" --3way"
else
	AMOPTS+=" --reject"
	APPLYOPTS+=" --reject --index"
fi

if $UTF8; then
	AMOPTS+=" --utf8"
else
	AMOPTS+=" --no-utf8"
fi

if $QUIET; then
	AMOPTS+=" --quiet"
else
	APPLYOPTS+=" --verbose"
fi

# Second form (--continue | --skip | --abort | --quit | --status | --resolve | --show-current-patch)
case "$ACTION" in
continue|skip|resolve)
	"action_$ACTION"
	;;
abort|quit|status|resolved|show-current-patch)
	"action_$ACTION"
	exit
	;;
*)
	fatal "$ACTION: Invalid action!"
	;;
esac

while [ "$next" -le "$last" ]; do
	patch="$(printf "%04i" "$next")"
	patch "$gitpatchdir/$patch"
	next
done

rm -rf "$gitdir/patch-apply"
